// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQleYCrHeU6dCjgmPxNpp17aDEWHK3Vk',
    appId: '1:307102859657:web:dfa21392dcb36bb00f2158',
    messagingSenderId: '307102859657',
    projectId: 'ipd1-511b5',
    authDomain: 'ipd1-511b5.firebaseapp.com',
    storageBucket: 'ipd1-511b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_aToGxOH5mUJq_WsQeDApnOZh1bedmiM',
    appId: '1:307102859657:android:bac535c07462f0300f2158',
    messagingSenderId: '307102859657',
    projectId: 'ipd1-511b5',
    storageBucket: 'ipd1-511b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_i8Re8pREPKs91VfFrR2bpXSAcE-7kf4',
    appId: '1:307102859657:ios:42d1c3b76a0d7dec0f2158',
    messagingSenderId: '307102859657',
    projectId: 'ipd1-511b5',
    storageBucket: 'ipd1-511b5.appspot.com',
    iosClientId: '307102859657-hju1f17jlq28uffu2q57fjlgva4vh10k.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_i8Re8pREPKs91VfFrR2bpXSAcE-7kf4',
    appId: '1:307102859657:ios:8afbc75368badbcf0f2158',
    messagingSenderId: '307102859657',
    projectId: 'ipd1-511b5',
    storageBucket: 'ipd1-511b5.appspot.com',
    iosClientId: '307102859657-sp1ov72etu61blrnf9hrofnl01reuar2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ipd.RunnerTests',
  );
}
